name: Deploy Portfolio to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies (if any)
      run: |
        if [ -f "package.json" ]; then
          npm ci
        fi
        
    - name: Build project (if needed)
      run: |
        if [ -f "package.json" ] && npm run build; then
          echo "Build completed"
        else
          echo "No build step required"
        fi
        
    - name: Replace API key placeholder
      run: |
        if [ -n "${{ secrets.GEMINI_API_KEY }}" ]; then
          sed -i 's/YOUR_GEMINI_API_KEY_PLACEHOLDER/${{ secrets.GEMINI_API_KEY }}/g' personal_ai.js
          echo "✅ API key injected successfully"
        else
          echo "⚠️ No GEMINI_API_KEY secret found - using placeholder"
        fi
        
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: '.'
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
